car:
    path:     /
    defaults: { _controller: "CarsBundle:Cars:index" }
    methods: [GET]

car_form:
    path:     /form/{id}
    defaults: { _controller: "CarsBundle:Cars:form", id: null }

car_remove:
    path:     /{id}
    defaults: { _controller: "CarsBundle:Cars:remove"}
    methods: [DELETE]

car_save:
    path:     /{id}
    defaults: { _controller: "CarsBundle:Cars:save", id: null }
    methods: [POST]



