CarsBundle\Entity\Car:
    type: entity
    table: cars
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        brand:
            type: string
            length: '25'
        color:
            type: string
            length: '25'
    lifecycleCallbacks: {  }
